POST http://localhost:9999/api/v1/login
Accept: application/json
Content-Type: application/json

{
    "usuario": "usuario1",
    "contrasena": "12345"
}

#Autenticacion incorrecta#

POST http://localhost:9999/api/v1/login
Accept: application/json
Content-Type: application/json

{
    "usuario": "usuario1",
    "contrasena": "12355"
}
