### Crear una tarea ###
POST http://localhost:9999/api/v1/tareas
Accept: application/json
Content-Type: application/json

{
    "titulo": "Lavar el coche",
    "fechaLimite": "2023-10-31",
    "completada": false,
    "usuarioId": 1,
    "etiquetaId": 2
}

### Obtener una tarea por ID ###
GET http://localhost:9999/api/v1/tareas/9
Accept: application/json

### Actualizar el estado de una tarea por ID ###
PUT http://localhost:9999/api/v1/tareas/1/estado
Accept: application/json
Content-Type: application/json

{
    "completada": true
}
### Obtener una tarea por ID ###
GET http://localhost:9999/api/v1/tareas
Accept: application/json

### Obtener todas las tareas por usuario ###
GET http://localhost:9999/api/v1/tareas/usuario/1
Accept: application/json

###Eliminar tarea con id válido###
DELETE http://localhost:9999/api/v1/tareas/14
Accept: application/json

###Eliminar tarea con id inválido###
DELETE http://localhost:9999/api/v1/tareas/100
Accept: application/json
